name: Deploy

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/p-stream
            git pull origin production
            if [ -d "private-providers/.git" ]; then
              git -C private-providers pull origin main
            else
              git clone https://github.com/xp-technologies-dev/private-providers private-providers
            fi
            pnpm i
            pnpm build
            pm2 restart pstream
